# Used for running the usage matrix via nginx locally, to test http auth etc
# as would be built for the prod deploy to fly.io
#
# For local development, just use ./scripts/server
services:
  web:
    build:
      context: .
      secrets:
        - nginx_auth
    ports:
      - "8080:80"

secrets:
  nginx_auth:
    file: ./nginx_auth.txt
