name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Clone from Azure: sip-adb-academies-datastore"
        run: |
          B64_PAT=$(printf ":%s" "${AZURE_DEVOPS_PAT}" | base64)
          git -c http.extraHeader="Authorization: Basic ${B64_PAT}" \
            clone --depth=1 \
            https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_git/sip-adb-academies-datastore
        env:
          AZURE_DEVOPS_PAT: ${{secrets.AZURE_DEVOPS_PAT}}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'

      - run: curl -sSL https://install.python-poetry.org | python3 -

      - run: ./scripts/bootstrap

      - run: ./scripts/generate-data-usage-csvs

      - run: 'echo "${DATABASE_STRUCTURE_CONTENTS}" > database_structure.csv'
        shell: bash
        env:
          DATABASE_STRUCTURE_CONTENTS: ${{secrets.DATABASE_STRUCTURE_CONTENTS}}

      - run: 'echo "${REPORTING_VIEWS_DEPENDENCIES_CONTENTS}" > reporting_views_dependencies.csv'
        shell: bash
        env:
          REPORTING_VIEWS_DEPENDENCIES_CONTENTS: ${{secrets.REPORTING_VIEWS_DEPENDENCIES_CONTENTS}}

      - run: 'echo "${PIPELINE_DEPENDENCIES_CONTENTS}" > pipeline_dependencies.json'
        shell: bash
        env:
          PIPELINE_DEPENDENCIES_CONTENTS: ${{secrets.PIPELINE_DEPENDENCIES_CONTENTS}}

      - run: ./scripts/build

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: deploy to fly
        run: flyctl deploy --remote-only --build-secret nginx_auth="${NGINX_AUTH}"
        env:
          NGINX_AUTH: ${{ secrets.NGINX_AUTH }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
